version: '3'
services:
  # go application
  app:
    container_name: "cryptowatch_worker"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"